import type { TowerStat, EnemyStat } from './types';

export const TOWERS: Record<string, TowerStat> = {
  basic_password: {
    damage: 8,
    range: 2.5,
    fireRate: 0.8,
    cost: 50,
    hp: 120,
    description: 'Una contraseña corta. Barata y débil.',
    educational: 'Las contraseñas cortas son adivinables en segundos. Cámbiala por algo más largo.',
  },
  strong_password: {
    damage: 18,
    range: 3.0,
    fireRate: 1.0,
    cost: 110,
    hp: 220,
    description: 'Contraseña larga con símbolos, números y mayúsculas.',
    educational:
      'Una contraseña de 14+ caracteres con variedad de símbolos tarda siglos en caer por fuerza bruta.',
  },
  mfa: {
    damage: 30,
    range: 3.5,
    fireRate: 0.9,
    cost: 180,
    hp: 260,
    description: 'Verifica identidad con un segundo factor.',
    educational:
      'La MFA bloquea el 99% de los ataques automatizados, incluso si tu contraseña se filtra.',
  },
  password_manager: {
    damage: 0,
    range: 4.0,
    fireRate: 0,
    cost: 140,
    hp: 200,
    splash: 0,
    description: 'Aura de protección: potencia torres cercanas.',
    educational:
      'Un gestor de contraseñas crea y guarda claves únicas y robustas para cada cuenta. Fin de la reutilización.',
  },
  phishing_detector: {
    damage: 12,
    range: 2.8,
    fireRate: 1.4,
    cost: 130,
    hp: 180,
    description: 'Detecta y aturde a los phishers.',
    educational:
      'Fíjate en el dominio, los remitentes inesperados y los enlaces acortados. Si dudas, no cliques.',
  },
  firewall: {
    damage: 14,
    range: 2.2,
    fireRate: 1.1,
    splash: 1.5,
    cost: 160,
    hp: 240,
    description: 'Daño en área a oleadas densas.',
    educational:
      'Un firewall inspecciona el tráfico y descarta paquetes maliciosos antes de que lleguen al servicio.',
  },
  soc_center: {
    damage: 4,
    range: 6.0,
    fireRate: 0.3,
    cost: 220,
    hp: 320,
    description: 'Centro de monitoreo. Revela amenazas ocultas.',
    educational:
      'Un SOC vigila logs 24/7 y detecta anomalías que un humano jamás vería. La visibilidad lo es todo.',
  },
};

export const ENEMIES: Record<string, EnemyStat> = {
  script_kiddie: {
    hp: 40,
    speed: 1.1,
    armor: 0,
    bounty: 6,
    damage: 1,
    description: 'Un hacker novato con herramientas prestadas.',
    educational: 'Son los más comunes, pero un *basic password* los frena.',
  },
  botnet: {
    hp: 25,
    speed: 1.4,
    armor: 0,
    bounty: 4,
    damage: 1,
    description: 'Ejército de máquinas zombi.',
    educational: 'Un DDoS desde una botnet. Apagas el volumen con firewalls.',
  },
  brute_force: {
    hp: 110,
    speed: 0.7,
    armor: 3,
    bounty: 18,
    damage: 3,
    description: 'Prueba millones de contraseñas por segundo.',
    educational: 'Solo contraseñas largas + MFA los detienen.',
  },
  phisher: {
    hp: 70,
    speed: 0.9,
    armor: 0,
    bounty: 14,
    damage: 2,
    description: 'Te convence para que le des tu contraseña.',
    educational: 'La ingeniería social evade la tecnología. La capacitación es clave.',
  },
  breach_ghost: {
    hp: 160,
    speed: 0.8,
    armor: 1,
    bounty: 24,
    damage: 2,
    description: 'Aparece de la nada con credenciales filtradas.',
    educational: 'Credenciales filtradas en la dark web. Cambia contraseñas y usa manager.',
    isHidden: true,
  },
  deepfake: {
    hp: 220,
    speed: 0.85,
    armor: 4,
    bounty: 32,
    damage: 4,
    description: 'Imita la voz de tu CEO para pedir transferencias.',
    educational: 'Biometría + MFA + verificación fuera de banda combaten deepfakes.',
  },
  ransomware_knight: {
    hp: 320,
    speed: 0.7,
    armor: 5,
    bounty: 40,
    damage: 5,
    description: 'Cifra tus datos y pide rescate.',
    educational: 'Backups 3-2-1 inmutables. Y, sobre todo, no pagar.',
  },
  zero_day_phantom: {
    hp: 380,
    speed: 0.95,
    armor: 3,
    bounty: 46,
    damage: 5,
    description: 'Explota una vulnerabilidad desconocida.',
    educational: 'Parchea pronto, segmenta, y ten SOC 24/7.',
  },
  boss_weak_passwords: {
    hp: 4500,
    speed: 0.4,
    armor: 8,
    bounty: 400,
    damage: 10,
    description: 'Millones de usuarios con "123456", "password" y "qwerty".',
    educational: 'La contraseña más usada del mundo sigue siendo "123456". No seas ese porcentaje.',
    isBoss: true,
  },
  boss_lord_reuse: {
    hp: 5200,
    speed: 0.45,
    armor: 6,
    bounty: 420,
    damage: 10,
    description: 'Misma contraseña en 47 sitios.',
    educational: 'Una brecha en un sitio expone los 46 restantes. Usa gestor y claves únicas.',
    isBoss: true,
  },
  boss_breach_master: {
    hp: 6800,
    speed: 0.5,
    armor: 5,
    bounty: 480,
    damage: 12,
    description: 'Invoca Breach Ghosts a mansalva.',
    educational: 'Rotación de claves, monitoreo de breach (HaveIBeenPwned) y respuesta rápida.',
    isBoss: true,
  },
  boss_phisher_king: {
    hp: 5800,
    speed: 0.55,
    armor: 4,
    bounty: 460,
    damage: 14,
    description: 'Manipula a tus torres y las vuelve contra ti.',
    educational: 'Phishing avanzado. Verifica identidad por canal separado.',
    isBoss: true,
  },
};
