import type { Achievement, LevelManifest, Pet, TowerKind, EnemyKind } from './types';

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'guardian_novato',
    name: 'Guardián Novato',
    description: 'Completa tu primer nivel de campaña.',
    reward: { coins: 50, xp: 50 },
    icon: 'shield',
  },
  {
    id: 'firewall_legend',
    name: 'Firewall Legend',
    description: 'Derrota 500 enemigos con el Firewall.',
    reward: { coins: 200, gems: 5 },
    icon: 'firewall',
  },
  {
    id: 'password_master',
    name: 'Password Master',
    description: 'Coloca 25 torres de Strong Password.',
    reward: { coins: 150, xp: 100 },
    icon: 'key',
  },
  {
    id: 'mfa_defender',
    name: 'MFA Defender',
    description: 'Gana una partida usando al menos 3 torres MFA.',
    reward: { coins: 200, gems: 5 },
    icon: 'mfa',
  },
  {
    id: 'cyber_champion',
    name: 'Cyber Champion',
    description: 'Completa la campaña con las 4 estrellas.',
    reward: { coins: 1000, gems: 50 },
    icon: 'trophy',
  },
  {
    id: 'first_blood',
    name: 'First Blood',
    description: 'Derrota a tu primer enemigo.',
    reward: { coins: 10 },
    icon: 'sword',
  },
  {
    id: 'no_damage',
    name: 'Impecable',
    description: 'Completa un nivel sin perder vidas.',
    reward: { coins: 300, xp: 200 },
    icon: 'heart',
  },
  {
    id: 'speedrunner',
    name: 'Speedrunner',
    description: 'Termina un nivel en menos de 60 segundos.',
    reward: { gems: 10 },
    icon: 'bolt',
  },
  {
    id: 'completionist',
    name: 'Completionist',
    description: 'Desbloquea todos los logros básicos.',
    reward: { gems: 25 },
    icon: 'star',
  },
  {
    id: 'phisher_hunter',
    name: 'Phisher Hunter',
    description: 'Derrota 50 phishers.',
    reward: { coins: 200, xp: 150 },
    icon: 'mask',
  },
];

export const PETS: Pet[] = [
  {
    id: 'byte',
    name: 'Byte',
    description: 'Un dron curioso que recolecta monedas.',
    passive: { kind: 'coin_boost', value: 0.1 },
    icon: 'drone',
  },
  {
    id: 'firewall_dog',
    name: 'Firewall Dog',
    description: 'Un buen chico que bloquea el primer ataque cada oleada.',
    passive: { kind: 'damage_boost', value: 0.05 },
    icon: 'dog',
  },
  {
    id: 'cyber_owl',
    name: 'Cyber Owl',
    description: 'Visión aguda: revela Breach Ghosts a mayor distancia.',
    passive: { kind: 'reveal_radius', value: 2 },
    icon: 'owl',
  },
  {
    id: 'password_panda',
    name: 'Password Panda',
    description: 'Mascota del aprendizaje. +XP global.',
    passive: { kind: 'xp_boost', value: 0.15 },
    icon: 'panda',
  },
  {
    id: 'hack_hunter',
    name: 'Hack Hunter Bot',
    description: 'Acelera cadencia de todas las torres.',
    passive: { kind: 'fire_rate_boost', value: 0.1 },
    icon: 'bot',
  },
];

// --- CAMPAÑA: 12 niveles de muestra + un schema replicable a 50 ---
function w(delay: number, ...groups: { kind: EnemyKind; count: number; interval: number }[]) {
  return { delay, groups };
}

export const LEVELS: LevelManifest[] = [
  {
    id: 'city-01',
    name: 'Amanecer en Cyber Fortress',
    environment: 'city',
    difficulty: 1,
    startingCoins: 200,
    startingLives: 20,
    waves: [
      w(3, { kind: 'script_kiddie', count: 6, interval: 0.9 }),
      w(8, { kind: 'script_kiddie', count: 10, interval: 0.7 }),
      w(12, { kind: 'botnet', count: 6, interval: 0.6 }),
    ],
  },
  {
    id: 'city-02',
    name: 'Primer Firewall',
    environment: 'city',
    difficulty: 1,
    startingCoins: 220,
    startingLives: 20,
    unlockedBy: 'city-01',
    waves: [
      w(3, { kind: 'script_kiddie', count: 8, interval: 0.7 }),
      w(8, { kind: 'botnet', count: 10, interval: 0.45 }),
      w(15, { kind: 'brute_force', count: 3, interval: 1.2 }),
    ],
  },
  {
    id: 'city-03',
    name: 'Phishing al Atardecer',
    environment: 'city',
    difficulty: 2,
    startingCoins: 240,
    startingLives: 18,
    unlockedBy: 'city-02',
    waves: [
      w(3, { kind: 'phisher', count: 4, interval: 1.0 }),
      w(10, { kind: 'phisher', count: 6, interval: 0.7 }, { kind: 'script_kiddie', count: 8, interval: 0.5 }),
      w(18, { kind: 'brute_force', count: 4, interval: 1.2 }),
    ],
  },
  {
    id: 'city-04',
    name: 'La Brecha',
    environment: 'city',
    difficulty: 2,
    startingCoins: 260,
    startingLives: 18,
    unlockedBy: 'city-03',
    waves: [
      w(2, { kind: 'breach_ghost', count: 3, interval: 1.5 }),
      w(8, { kind: 'script_kiddie', count: 10, interval: 0.4 }),
      w(14, { kind: 'breach_ghost', count: 4, interval: 1.2 }),
      w(20, { kind: 'brute_force', count: 5, interval: 1.0 }),
    ],
  },
  {
    id: 'city-05',
    name: 'Rey de las Contraseñas Débiles',
    environment: 'city',
    difficulty: 3,
    startingCoins: 300,
    startingLives: 20,
    unlockedBy: 'city-04',
    waves: [
      w(2, { kind: 'script_kiddie', count: 10, interval: 0.4 }),
      w(8, { kind: 'brute_force', count: 5, interval: 0.8 }),
      w(15, { kind: 'botnet', count: 12, interval: 0.3 }),
      w(22, { kind: 'boss_weak_passwords', count: 1, interval: 1 }),
    ],
  },
  {
    id: 'school-01',
    name: 'Aula Expuesta',
    environment: 'school',
    difficulty: 2,
    startingCoins: 250,
    startingLives: 18,
    unlockedBy: 'city-05',
    waves: [
      w(3, { kind: 'phisher', count: 4, interval: 1.0 }),
      w(8, { kind: 'script_kiddie', count: 12, interval: 0.4 }),
      w(15, { kind: 'brute_force', count: 4, interval: 1.0 }),
    ],
  },
  {
    id: 'bank-01',
    name: 'Bóveda Digital',
    environment: 'bank',
    difficulty: 3,
    startingCoins: 280,
    startingLives: 15,
    unlockedBy: 'school-01',
    waves: [
      w(2, { kind: 'botnet', count: 14, interval: 0.3 }),
      w(8, { kind: 'brute_force', count: 6, interval: 0.9 }),
      w(15, { kind: 'deepfake', count: 2, interval: 2 }),
    ],
  },
  {
    id: 'bank-02',
    name: 'Lord Reuse',
    environment: 'bank',
    difficulty: 4,
    startingCoins: 320,
    startingLives: 15,
    unlockedBy: 'bank-01',
    waves: [
      w(2, { kind: 'script_kiddie', count: 10, interval: 0.4 }),
      w(8, { kind: 'phisher', count: 6, interval: 0.7 }),
      w(15, { kind: 'brute_force', count: 6, interval: 0.8 }),
      w(22, { kind: 'boss_lord_reuse', count: 1, interval: 1 }),
    ],
  },
  {
    id: 'hospital-01',
    name: 'Monitor Vital',
    environment: 'hospital',
    difficulty: 3,
    startingCoins: 260,
    startingLives: 18,
    unlockedBy: 'bank-02',
    waves: [
      w(2, { kind: 'script_kiddie', count: 8, interval: 0.5 }),
      w(8, { kind: 'ransomware_knight', count: 2, interval: 2 }),
      w(16, { kind: 'botnet', count: 12, interval: 0.35 }),
    ],
  },
  {
    id: 'datacenter-01',
    name: 'Centro de Datos',
    environment: 'datacenter',
    difficulty: 4,
    startingCoins: 300,
    startingLives: 15,
    unlockedBy: 'hospital-01',
    waves: [
      w(2, { kind: 'breach_ghost', count: 4, interval: 1.2 }),
      w(8, { kind: 'zero_day_phantom', count: 2, interval: 2 }),
      w(16, { kind: 'deepfake', count: 3, interval: 1.6 }),
    ],
  },
  {
    id: 'datacenter-02',
    name: 'The Breach Master',
    environment: 'datacenter',
    difficulty: 5,
    startingCoins: 360,
    startingLives: 15,
    unlockedBy: 'datacenter-01',
    waves: [
      w(2, { kind: 'breach_ghost', count: 6, interval: 0.8 }),
      w(8, { kind: 'brute_force', count: 6, interval: 0.8 }),
      w(15, { kind: 'zero_day_phantom', count: 2, interval: 2 }),
      w(22, { kind: 'boss_breach_master', count: 1, interval: 1 }),
    ],
  },
  {
    id: 'datacenter-03',
    name: 'The Phisher King',
    environment: 'datacenter',
    difficulty: 5,
    startingCoins: 400,
    startingLives: 12,
    unlockedBy: 'datacenter-02',
    waves: [
      w(2, { kind: 'phisher', count: 10, interval: 0.4 }),
      w(8, { kind: 'deepfake', count: 4, interval: 1.4 }),
      w(15, { kind: 'phisher', count: 12, interval: 0.3 }),
      w(22, { kind: 'boss_phisher_king', count: 1, interval: 1 }),
    ],
  },
];

export const TOWER_ORDER: TowerKind[] = [
  'basic_password',
  'strong_password',
  'mfa',
  'password_manager',
  'phishing_detector',
  'firewall',
  'soc_center',
];
